# Generated by Django 3.2.9 on 2021-11-26 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='SmsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(default='', max_length=500)),
                ('message_date', models.DateField(default='2020-12-12')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.contacts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('message_date', models.DateField(default='2020-12-12')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.contacts')),
            ],
        ),
    ]
