# Generated by Django 3.2.9 on 2021-12-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.message')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapi.tag')),
            ],
        ),
    ]
