# Generated by Django 3.2.9 on 2021-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0003_messagetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(related_name='message_tags', through='capstoneapi.MessageTag', to='capstoneapi.Tag'),
        ),
    ]
